### ISSUE TITLE
Removal of id

### ISSUE THREAD

**Issue by rm-code** [rm-code/PZ-UI-Overhaul#2]
```lua
local ID = UIO.maxID + 1;
UIO.maxID = ID;
```
I know this is a remnant from the vanilla code and I'm fairly sure that it actually isn't used anywhere. Might make sense to dig through the vanilla files and see if it can be left out.

Leaving this here so I don't forget.

**Comment by blind-coder** [comment]
I added this on purpose, mainly because I like keeping track of things.
Also, I used the ID as an index in the BaseElement.children object. If that object is necessary in the first place - and if it makes sense to enumerate them globally, as opposed to just using table.insert() - remains to be seen, though.
